language: node_js

node_js:
  - "0.10"

branches:
  except:
    - gh-pages

env:
  global:
    - REPO="git@github.com:hackfoldr/hackfoldr"
    - secure: "Z0x2sQ0zWwLF3DAAggqLoYI5gs6Ys2b5wrfmt5CYEJY0JiYiaAdIHiSd3v4g\n4fGEIQJusV/2qbNSMinpsyyGStMyjL5mTk3NKUip72tKbKb8H+6HtbYPK91B\ngKFchLxTrfY596ulsX752BlkFM8b4jcGRlpjIaX9RAdIncU9Qc0="
    - GOOGLE_API_BROWSER_APPLICATION_KEY="AIzaSyCHm8NgD_p5F_-e7euH8BZiB4wSB8pOZ2A"

after_success: .travis/after_success.sh
